FROM golang:1.13

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list  && \
    apt update && apt install nodejs yarn -y

RUN yarn add gatsby-remark-vscode

WORKDIR /tkbyexample

ENTRYPOINT ["sh", "-c"]
CMD ["make", "dev"]
